# Generated by Django 5.2.11 on 2026-02-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.software', verbose_name='ซอฟต์แวร์ที่ติดตั้ง'),
        ),
    ]
