# Generated by Django 5.2.11 on 2026-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-end_time']},
        ),
        migrations.RemoveField(
            model_name='computer',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='installed_software',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='pc_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='pc_type',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='session_start',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_type',
        ),
        migrations.RemoveField(
            model_name='software',
            name='version',
        ),
        migrations.AddField(
            model_name='usagelog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='software_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='user_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
