# Generated by Django 5.2.11 on 2026-02-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0002_status_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='computer',
            name='installed_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.software', verbose_name='ซอฟต์แวร์ที่ติดตั้ง'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
