# Generated by Django 5.2.11 on 2026-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0002_booking_siteconfig_status_alter_usagelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ License'),
        ),
        migrations.AddField(
            model_name='software',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='ชื่อรายการ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('Software', 'Software (ทั่วไป)'), ('AI', 'AI Tool (ปัญญาประดิษฐ์)')], default='Software', max_length=20, verbose_name='ประเภท'),
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(default='', max_length=50, verbose_name='แพ็กเกจ (Package)'),
            preserve_default=False,
        ),
    ]
